name: argtest
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - numpy>=2
  - matplotlib
  - tszip
  - msprime
  - Snakemake=9.16.2
  - snakemake-executor-plugin-cluster-generic
  - pytest
  - pip
  - pip:
      - "tskit @ git+https://github.com/nspope/tskit.git@73d8cd922482475020ae01180cae95bf5abbf067#subdirectory=python"
